name: PR Test

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm install
      - name: Waiting for 200 from the Netlify Preview
        uses: rphansen91/wait-for-netlify-action@v1.0.3
        id: wait-for-netlify-preview
        with:
          site_name: "haikugpt"
          max_timeout: 900 # Increased timeout to 900 seconds
      - name: Run Tests
        run: npm test
        env:
          NETLIFY_PREVIEW_URL: ${{ steps.wait-for-netlify-preview.outputs.url }}