name: Snapshot Workflow

on: [push]

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Take screenshot
        uses: lannonbr/puppeteer-screenshot-action@1.0.0
        with:
          urls: 'https://your-website.com'

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshots/