name: Snapshot

on: [push]

jobs:
  capture:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Take snapshots of the application
      uses: lannonbr/puppeteer-screenshot-action@1.0.0
      with:
        urls: '["http://localhost"]'

    - name: Upload Screenshots
      uses: actions/upload-artifacts@v3
      with:
        name: screenshots
        path: screenshots/