name: Snapshot
on: push
jobs:
  capture:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lannonbr/puppeteer-screenshot-action@1.0.0
        with:
          url: 'https://your-website.com'
          path: './screenshots/snapshot.png'
      - uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: ./screenshots