name: Haiku Snapshot
on: pull_request_target
jobs:
  take-screenshot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Haiku Snapshot
      uses: 'lannonbr/puppeteer-screenshot-action@1.0.0'
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with:
        url: 'https://llminate-labs.github.io/haiku/'
    - name: Upload screenshots
      uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: screenshots/
    - name: Comment with image
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          const screenshots = fs.readdirSync(path.join(process.env.GITHUB_WORKSPACE, 'screenshots'), 'utf8');
          console.log(context.issue, screenshots);
          return Promise.all(screenshots.map(screenshot => {
            const base64 = fs.readFileSync(path.join(process.env.GITHUB_WORKSPACE, 'screenshots', screenshot)).toString('base64');
            return github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.name,
              issue_number: context.issue.number,
              body: `![Generated Image](data:image/png;base64,${base64})`,
            })
          }));
